FROM --platform=linux/amd64/v3 node:20.10.0-alpine

EXPOSE 5173
WORKDIR /app

COPY ./package.json .
COPY ./yarn.lock .

RUN npm install -g yarn --force
RUN yarn install

COPY . .
COPY ./index.html ./vite.config.ts ./.gitignore ./

CMD [ "yarn", "dev" ]