version: '3'

services:
  fmtl-net:
    container_name: fmtl-net
    build:
      context: ../
      dockerfile: .docker/Dockerfile.dev
    ports:
      - 5173:5173
    volumes:
      - ../src:/app/src